language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t vishalkallem/react_app -f Dockerfile.dev .

script:
    - docker run -e CI=true vishalkallem/react_app npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "Enter your bucket_name"
    bucket_path: "Enter your bucket_path"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"