version: '3.8'
services: 
    react-app:
        stdin_open: True
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - .:/app
            - /app/node_modules